name: ReichsCore
main: me.nils.reichsmp.reichscore.main.ReichsCore
version: 1.0
api-version: 1.20

description: Core plugin for ReichsMP plugin network.
author: NilusNilus
website: https://github.com/ReichsMP